### ISSUE TITLE
Cannot retrieve the window id of the to be recorded window - on Windows with WSL

### ISSUE THREAD

**Issue by oren** [sassman/t-rec-rs#33]
**Describe the bug**
t-rec
```
Error: Cannot retrieve the window id of the to be recorded window.

Caused by:
    Display parsing error
```

**To Reproduce**
a. install dependencies
sudo apt-get install libx11-dev

(based on https://gist.github.com/pshah123/963db645047597723956af13ab87b73a)

wget https://www.imagemagick.org/download/ImageMagick.tar.gz
tar xvzf ImageMagick.tar.gz
cd ImageMagick-*
./configure
make
sudo make install
sudo ldconfig /usr/local/lib

(ImageMagick 7.0.10-53 Q16 x86_64 2020-12-31)

b. install t-rec
cargo install -f t-rec

**Version Numbers of your System:**
 * Microsoft Windows [Version 10.0.18363.1198]
* WSL version 1
* Ubuntu 18.04 TLS

**Additional context**
xwininfo -root -tree -int
```
xwininfo: error: unable to parse display name ""
```

**Comment by sassman** [comment]
That is an interesting one, since this is WSL, I guess you just used a terminal not a X window based terminal? Maybe you can post a screenshot from the terminal that you have used?

However, by the error message below this is pretty much to be expected.

```plain
xwininfo: error: unable to parse display name ""
```

For `t-rec` to functioning a X Server is needed, so in your case there is not an X Server nor a DISPLAY that can be captured. I'm not an WSL expert, but I guess there is no way that this would work like this (without a running X Server)

**Comment by Jacrys** [comment]
@oren,

Likely this won't work until the new version of WSL2 comes out of slow ring at the earliest, at least natively.  As of current (unless you are in the fast ring), windows doesn't pack an X server, and while you can spin one up, it is kind of hackish currently.  Additionally, most of the time, WSL is used via the WSL bash terminal or via Windows Terminal, so, since this is predicated on the need for an X-Server (and therefore, a window running in the X-server space), to get this to work, you would need to launch an X-based term program from your Windows term program and then start t-rec from the X-based term program's window.  There are a couple of X Servers for Windows available in the MS Store if you really want to go down that route,   

Even once full X support and GPU acceleration are added to W10, it is very likely to be niche at best.

**Comment by Jacrys** [comment]
I am not sure how feasible or possible this would be using the win-32 branch.  It would at that point be a windows process, but may or may not be complicated by the fact you would be using it from a Linux command line.

**Comment by sassman** [comment]
I believe we can close this issue as can't fix.

At this point I want to pint out that there is a windows native branch that already works but is not production grade. You might give this a try.

feat/win32-support
